name: Create DB Table

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Scp Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.EC_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: "ubuntu"
          source: "scripts/create_rds_table.py"
          target: "/home/ubuntu"
      - name: Run create_rds_table.py Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{vars.EC_IP}}
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/scripts && python3 create_rds_table.py
